name: CI for Multiple ROS2 Packages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      package_list: |
        image_perception
        image_projection
        usb_camera
        image_recognition_msgs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 (Eloquent)
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: eloquent

      - name: Install dependencies using rosdep
        run: |
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro eloquent -y

      - name: Add ROS2 GPG key
        run: |
          curl -sSL http://packages.ros.org/ros.key | sudo tee /etc/apt/trusted.gpg.d/ros-archive-keyring.gpg > /dev/null

      - name: Add ROS2 repository to sources list
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2-latest.list'

      - name: Update apt and install necessary packages
        run: sudo apt-get update

      - name: Build all packages
        run: |
          for pkg in ${{ env.package_list }}; do
            echo "Building package: $pkg"
            colcon build --packages-select $pkg || true
          done

      - name: Run tests for all packages
        run: colcon test --event-handlers console_cohesion+

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: colcon_ws/log
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: colcon_ws/log/latest_test
        if: always()
