name: CI for Multiple ROS2 Packages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      package_list: |
        image_recognition_msgs
        usb_camera
        pan_tilt_camera
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 (Eloquent)
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: eloquent

      - name: Install dependencies using rosdep
        run: |
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro eloquent -y

      - name: Build all packages
        run: |
          for pkg in ${{ env.package_list }}; do
            echo "Building package: $pkg"
            colcon build --packages-select $pkg || true
          done

      - name: Run tests for all packages
        run: |
          colcon test --event-handlers console_cohesion+

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: colcon_ws/log
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: colcon_ws/log/latest_test
        if: always()
