name: Build and Test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [foxy, humble]
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4

      - name: Building and testing on ROS2 ${{ matrix.ros2-distro }}
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          apt-packages: libssh-dev libopencv-dev ros-${{ matrix.ros2-distro }}-cv-bridge
          ros2-distro: ${{ matrix.ros2-distro }}
