name: image_recognition_msgs

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: image_recognition_msgs Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4

      - name: Building and testing on ROS2 Humble
        uses: mjlee111/ros2-ci@v1.0.0
        with:
          apt-packages: libssh-dev libopencv-dev ros-humble-cv-bridge
          ros2-distro: humble
          specific-package: image_recognition_msgs