name: Lint
on: push
jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, flake8, pep257, lint_cmake, xmllint, copyright]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name: |
          image_recognition_msgs
          usb_camera
          pan_tilt_camera
          
